// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef fltk_h
#define fltk_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
extern void btn01Cb(Fl_Button*, void*);
#include <FL/Fl_Box.H>
extern void btnRunCb(Fl_Button*, void*);
#include <FL/Fl_Value_Output.H>

class fltkWin {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *win01;
  Fl_Output *fnameOut;
  Fl_Button *btn01;
  Fl_Output *outFirmware;
  Fl_Output *outMcu;
  Fl_Output *outFreq;
  Fl_Button *btnRun;
  Fl_Value_Output *pbOut;
};
#endif
